"use client";

import { useRef } from "react";

type Props = { name: string; card: string; total: string };

// The real share card for one package, staged as a post that unfurled it, tilting toward the pointer.
export function CardShowcase({ name, card, total }: Props) {
  const stageRef = useRef<HTMLDivElement>(null);

  function onMove(e: React.PointerEvent) {
    const el = stageRef.current;
    if (!el || e.pointerType !== "mouse") return;
    const r = el.getBoundingClientRect();
    const x = (e.clientX - r.left) / r.width - 0.5;
    const y = (e.clientY - r.top) / r.height - 0.5;
    el.style.setProperty("--rx", `${(-y * 8).toFixed(2)}deg`);
    el.style.setProperty("--ry", `${(x * 10).toFixed(2)}deg`);
  }

  function onLeave() {
    const el = stageRef.current;
    if (!el) return;
    for (const p of ["--rx", "--ry"]) el.style.removeProperty(p);
  }

  return (
    <div
      ref={stageRef}
      onPointerMove={onMove}
      onPointerLeave={onLeave}
      className="relative mx-auto w-full max-w-[560px] py-6 [perspective:1100px]"
    >
      <div
        className="relative transition-transform duration-300 ease-out motion-reduce:transition-none"
        style={{ transform: "rotateX(var(--rx, 0deg)) rotateY(var(--ry, 0deg))", transformStyle: "preserve-3d" }}
      >
        {/* The post that unfurled the link */}
        <div
          className="relative rounded-2xl border border-line bg-surface p-4 sm:p-5"
        >
          <div className="flex items-center gap-3">
            <span className="flex size-9 items-center justify-center rounded-full bg-yellow-wash font-semibold text-ink">
              {name.replace(/^@/, "").charAt(0).toUpperCase()}
            </span>
            <div className="leading-tight">
              <div className="text-sm font-semibold text-ink">You</div>
              <div className="text-xs text-muted">just now</div>
            </div>
          </div>
          <p className="mt-3 text-[15px] text-ink">
            {name} is at {total} downloads 🧡{" "}
            <span className="text-accent">shipstat{card.split("?")[0].replace("/api/card", "")}</span>
          </p>
          {/* eslint-disable-next-line @next/next/no-img-element -- generated PNG */}
          <img
            src={card}
            alt={`The shipstat card for ${name}`}
            width={1200}
            height={630}
            loading="lazy"
            className="mt-3 w-full rounded-xl border border-line"
          />
          <div className="mt-2.5 flex items-center gap-1.5 text-xs text-muted">
            <svg viewBox="0 0 16 16" aria-hidden className="size-3.5">
              <path d="M6.5 9.5 9.5 6.5M7 4.5l1-1a2.8 2.8 0 0 1 4 4l-1 1M9 11.5l-1 1a2.8 2.8 0 0 1-4-4l1-1" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" />
            </svg>
            Link preview, generated by shipstat
          </div>
        </div>
      </div>
    </div>
  );
}
